# 生产环境配置
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: 
    password: 
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      min-idle: 1
      max-idle: 10
      max-total: 500
      max-wait-millis: 10000
      initial-size: 5
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true






